import Header from "@/components/layout/header/Header";
import "./assets/styles/globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";

import localFont from "next/font/local";
import { Provider } from "react-redux";
import { store } from "@/store/store";
import { ReduxProvider } from "@/providers/ReduxProvide";

const myFont = localFont({
  src: './assets/fonts/Jura-VariableFont_wght.ttf',
  display: 'swap',
})

export const metadata: Metadata = {
  title: "Vitrima",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <ReduxProvider>
    <html lang="ru">
      <body className={myFont.className}>
        <Header />
        {children}
      </body>
    </html>
    </ReduxProvider>
  );
}
